version: '3.1'
services:
 
 amqp:
  restart: always
  image: marcelmaatkamp/steemit-amqp
  build: .
  environment:
   - RABBITMQ_HOSTNAME=rabbitmq
   - RABBITMQ_EXCHANGE=steemit
  volumes:
   - ./credentials.py:/app/mycredentials.py
