version: '3.1'
services:

 rabbitmq:
  image: marcelmaatkamp/rabbitmq-mqtt-ldap
  restart: always
  hostname: rabbitmq
  environment:
   RABBITMQ_NODENAME: rabbitmq@rabbitmq
  volumes:
   - rabbitmq:/var/lib/rabbitmq/mnesia
  logging:
   options:
    max-size: 50m
 
 amqp:
  restart: always
  image: marcelmaatkamp/steemit-amqp
  build: .
  environment:
   - RABBITMQ_HOSTNAME=rabbitmq
   - RABBITMQ_EXCHANGE=amq.topic
  volumes:
   - ./credentials.py:/app/mycredentials.py
    
volumes:
 rabbitmq:
