version: '3.1'
services:
 
 amqp:
  restart: always
  build: .
  command: python amqp.py
  environment:
   - RABBITMQ_HOSTNAME=rabbitmq
   - RABBITMQ_EXCHANGE=steemit
  # extra_hosts:
  #  - "rabbitmq:172.20.0.5"
  volumes:
   - ./credentials.py:/app/mycredentials.py
